# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/bouquet/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter whyred tulip,$(TARGET_DEVICE)),)

endif
